<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>S142VJetpackAcceleration</AssemblyName>
    <RootNamespace>S142VJetpackAcceleration</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="HarmonyX" Version="2.10.2" />
    <PackageReference Include="LethalCompany.GameLibs.Steam" Version="81.0.5-ngd.0" />
  </ItemGroup>
</Project>
