#!/usr/bin/env python3
"""Render source constants from exact dependency evidence; never compile/build."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / 'SourceEvidence/BMAFR1Instrumentation/EXACT_DEPENDENCY_CONTRACTS.json'
DEST = ROOT / 'Patches/S142AKBMAFR1I1/ContractData.cs'


def render(data):
    rows = []
    for assembly in data['assemblies']:
        for m in assembly['methods']:
            args = 'new string[] { ' + ', '.join(json.dumps(p) for p in m['parameter_types']) + ' }'
            locals_ = 'new string[] { ' + ', '.join(json.dumps(p) for p in m['locals']) + ' }'
            regions = 'new int[][] { ' + ', '.join('new int[] { ' + ', '.join(map(str, [e['kind'], e['try_start'], e['try_end'] - e['try_start'], e['handler_start'], e['handler_end'] - e['handler_start']])) + ' }' for e in m['exception_handlers']) + ' }'
            rows.append('            new MethodContract(' + ', '.join([
                json.dumps(m['owner']), json.dumps(m['name']), json.dumps(m['access']),
                str(m['static']).lower(), json.dumps(m['return_type']), args, json.dumps(m['il_sha256']), locals_, str(m['max_stack']), str(m['init_locals']).lower(), regions]) + '),')
    return '\n'.join([
        '// Generated by AnalysisTools/generate_s142ak_bmafr1i1_contract_data.py; do not hand-edit.',
        'namespace S142AKBMAFR1I1', '{', '    internal static class ContractData', '    {',
        '        internal static readonly MethodContract[] Methods = new[]', '        {',
        *rows, '        };', '    }', '}', '',
    ])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = render(json.loads(EVIDENCE.read_text()))
    if args.check:
        if DEST.read_text() != result:
            raise SystemExit('ContractData.cs differs from exact dependency evidence')
        print('Generated contract data PASS')
    else:
        DEST.write_text(result)
